# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161ccd92b44ac91617bccf4c21acf6777d91d64874d444045afb59e95d9a6ccb4bc6d02b3de7b304794d216cec53e5e544c38ae089c1389246185145b9c27d5f

test:
  secret_key_base: c07e54f09a38b7c9fa4dcfe3fe4c5c54076fde22155ac71ff07fc5503e9e4e326e9e891219f2982ecd272c86ee0a990adfa41e171cb14a2b8665178eff218b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
